[build]
  publish = "/"
  command = "echo 'No build command needed for static HTML site'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Exclure les fichiers volumineux du déploiement
[build.processing]
  skip_processing = true

[build.processing.images]
  compress = true

# Ignorer les fichiers volumineux
[build.environment]
  NETLIFY_LARGE_MEDIA = "true"
